config/routes.rb
Radiotec2::Application.routes.draw do
  get "home/index"
  get "home/programas" => "home#programs", :as => :programs_home
  get "home/horarios" => "home#schedules",:as => :schedules_home
  get "home/acerca" => "home#about",:as => :about_home
  resources :programs

  root "home#index"

  

end

app/models/program.rb
class Program < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@last = Program.last
  	@before_last = Program.first
  end

  def programs
  	@programs = Program.all
  end
  
  def schedules
  end

  def about
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render action: 'show', status: :created, location: @program }
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/home/about.html.erb
<div class="page_hone">
            <h1>RadioTec</h1>
        </div>

        <section id="acerca_section">
            <article>
                <h2>Historia</h2>
                <pre><h3>
El Proyecto RadioTec es el resultado de la suma de esfuerzos de las autoridades del ITCH II para satisfacer la necesidad de comunicación de la Comunidad Bisonte. Éste era, es y será siempre un reto que fue asumido de frente y con el único objetivo de mejorar la calidad de nuestra institución al tiempo de exigirse estar a la vanguardia tecnológica que los alumnos merecen. Se inicia la implementación de RadioTec con el apoyo del Lic. Gabriel Salazar Hernández, Director del ITCH II, el Ing. Gerardo Ceniceros Reyes, Subdirector de Servicios Administrativos, la M.C. Rocío Quiñónez Moreno, Subdirectora de Planeación y Vinculación y el Arq. Armando Serrano Salomón, Subdirector Académico.

Se inician labores el 2 de febrero de 2013 con el Loc. y estudiante de Ingeniería Industrial Dante Francisco Olvera Barrios como Director Operativo del Proyecto RadioTec y el Ing. Luis Raúl Baray Martínez como Director Ejecutivo del Proyecto RadioTec, apoyados por un grupo de alumnos y maestros fungiendo como locutores, operadores de cabina y reporteros. 
                </h3></pre>
            </article>

            <article>
                <h2>Misión</h2>
                <pre><h3>
Ser un medio digital a la vanguardia tecnológica, de difusión de la cultura y la investigación, así como la comunicación de la información más relevante, enfocando sus actividades en pro de la formación y el fomento de los valores de la comunidad estudiantil que conforma el ITCH II y la sociedad.
                </h3></pre>
            </article>
            
            <article>
                <h2>Visión</h2>
                <pre><h3>
Ser una radio estudiantil pionera y a la vanguardia en los medios de comunicación, consolidada a través de su calidad informativa.
                </h3></pre>
            </article>

            <article>
                <h2>Objetivo General</h2>
                <pre><h3>
Ofrecer un medio de comunicación digital, destacando los cambios y mejoras que vive la comunidad estudiantil del Instituto Tecnológico de Chihuahua II, siendo además un vínculo entre autoridades y alumnos.
                </h3></pre>
            </article>

              <article>
                <h2>Imagen</h2>
                <pre><h3>
Define el valor de la comunicación, y de la importancia que ésta tiene para el ITCH II al mantener su nombre grabado en oro. Como fondo el horizonte que refleja el futuro; y frente a él, el logotipo por excelencia de la radiocomunicación, un micrófono de radio representado como un bisonte, encaminada hacia éste una manada de bisontes que avanzan juntos hacia el progreso. Finalmente en la parte baja un bisonte mirando hacia atrás para recordarnos que siempre hay un pasado que edifica nuestro futuro; Nuestra frase emblemática por excelencia, <strong>Es bueno ser grande, pero es mas grande ser un Bisonte”</strong>“ acentúa la imagen.
                </h3></pre>
            </article>

            <article>
                <h2>Logotipo Oficial</h2>
                <pre><h3>
Un micrófono antiguo de radio representando lo antigua pero esencial que es la comunicación en la vida diaria. El micrófono es coronado por dos cuernos que representan la unión de los Bisontes y la persistencia de los valores que nos caracterizan. La base del micrófono se une a un círculo blanco, que simboliza la comunicación y difusión de los Bisontes hacia todo el planeta, a través de la red mundial (Internet). El círculo exterior simboliza un futuro que describiremos aquí cuando se haya convertido en el presente. 
                </h3></pre>
            </article>
            
            <article id="acerca_img">
                <img src="<%=image_url('ImagenRadioTec.jpg')%>">
            </article>

        </section>

app/views/home/index.html.erb
<section id="first_section">
            <div class="row-fluid">
                <article class="green_banner span6" id="welcome_banner">
                    <figure>
                        <img src="<%= image_url('radiotec_logo.png') %>" id="banner_logo" alt="radiotec_logo">
                    </figure>
                    <h1 id="radio_title">
                        La radio cultural <br> del instituto Tecnológico de Chihuahua II
                    </h1>
                </article>   

                <a href="radio.html">
                    <article class="green_banner span5 offset1" id="listen_banner">
                        <h2>
                            Da click para escucharnos
                        </h2>
                        <figure>
                            <img src="<%= image_url('play_logo.png') %>" id="play_logo" alt="play_logo">
                        </figure>  
                    </article>   
                </a> 

               
                <article class="radio_banner span6" id="radio1_banner">
                    <h3>
                        <span><%= @before_last.name %></span><br>
                        <br><%= @before_last.desc %>
                        
                    </h3>
                    <figure>
                        <img src="<%= image_url('radio1_img.jpg') %>" id="radio1_img" alt="radio1_img">
                    </figure>
                </article>
                
                
                    <a href="https://twitter.com/radiotecitchii">
                    <article class="social_banner span5 offset1" id="twitter_banner">
                        <h3>
                            Mandanos tus peticiones<br>
                            <span>@RadioTecITCHII</span>
                        </h3>
                        
                        <figure>
                            <img src="<%= image_url('twitter_logo.png') %>" alt="twitter_logo" id="twitter_logo"/>
                        </figure>                
                    </article>
                </a>

                 <a href="https://www.facebook.com/radiotec.itchii">
                    <article class="social_banner span5 offset1" id="twitter_banner">
                        <h3>O Tus Comentarios</h3>
                        <figure>
                            <img src="<%= image_url('fb_logo.png') %>" alt="fb_logo" id="fb_logo"/>
                        </figure>                
                    </article> 
                 </a>  
        
                
            </div>
        </section>
        <footer>
            <div class="row-fluid">
                <article class="radio_banner span6" id="radio2_banner">  
                    <h3>
                        <strong>
                            <span>
                                <%= @last.name %> 
                            </span>
                        </strong><br><br>
                            <%= @last.desc %>
                    </h3>
                        
                    <figure>
                        <img src="<%= image_url('radio2_img.jpg') %>" id="radio2_img" alt="radio2_img">
                    </figure>
                </article> 
                <div class="row-fluid">
                    <a href="mailto:someone@example.com?Subject=Contacto RadioTECII" target="_top">
                        <article class="radio_banner span5 offset1" id="radio3_banner">
                        <h3>
                        <strong><span>
                            ¿Te interesa ser parte de nuestro equipo?</span><br>
                        </strong><br>
                        
                        ¡Contactanos!
                        </h3>
                        
                        <figure>
                            <img src="<%= image_url('radio3_img.png') %>" id="radio3_img" alt="radio3_img">
                        </figure>
                    </article>
                    </a>
                </div>
            </div>
        </footer>

app/views/home/programs.html.erb
<section id="programs_section">
	<div class="page_hone">
        <h1>Conoce nuestros programas</h1><br>
        <h2>Puedes consultar nuestros <%= link_to "Horarios", schedules_home_url %> para que no te pierdas nuestra programación.</h2>  
    </div>
	<% @programs.each do |program| %>
		<article class="program_item">
	        <h2 class="program_title">
	        	<%= program.name %>
	        </h2>
	        <figure class="program_figure">
	            <img src="img/radio1_img.jpg" alt="program1img">
	        </figure>
	        <h3 class="program_desc">
	           <%= program.desc %>
	        </h3>
	    </article>	
	<% end %>	
</section>

app/views/home/schedules.html.erb
<div class="page_hone">
            <div class="row-fluid">
            <table id="schedule_table" class="offset2">
                <tr>
                    <th><span>Hora/Dia</span></th>
                    <th>Lunes</th>
                    <th>Martes</th>
                    <th>Miércoles</th>
                    <th>Jueves</th>
                    <th>Viernes</th>
                    <th>Sábado</th>
                    <th>Domingo</th>
                </tr>
                <tr>
                    <th>6:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <th>7:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <th>8:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>

                <tr>
                    <th>9:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>10:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>11:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>12:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>13:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>14:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>15:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>16:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>17:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>18:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>19:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>20:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>21:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>22:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>23:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>00:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>1:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>2:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>3:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>4:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th>5:00</th>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Radiotec2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
    	<nav>
            <ul>
                <a href="/">
                	<img src="<%=image_url('radiotec_logo.png') %>"  id="header_logo" alt="radiotec_logo">
                </a>
                <li>
                    <%= link_to "Programas", programs_home_url %>
                </li>
                <li>
                	<%= link_to "Horarios", schedules_home_url %>
                </li>
                <li>
                	<%= link_to "Acerca", about_home_url %>
                </li>
                <li>
                	<a href="mailto:someone@example.com?Subject=Contacto RadioTECII">Contacto</a>
                </li>
            </ul>
        </nav>
    </header>

<%= yield %>

</body>
</html>

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Descripción %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar Programa" %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @program %> |
<%= link_to 'Atras', programs_path %>

app/views/programs/index.html.erb
<h1>Programas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Foto</th>
      <th>Creado</th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td><%= program.desc %></td>
        <td></td>
        <td><%= localize(program.created_at, :format => :long) %></td>
        <td><%= link_to 'Mostrar', program %></td>
        <td><%= link_to 'Editar', edit_program_path(program) %></td>
        <td><%= link_to 'Eliminar', program, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Programa', new_program_path %>

app/views/programs/new.html.erb
<h1>Nuevo Programa</h1>

<%= render 'form' %>

<%= link_to 'Atras', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @program.name %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @program.desc %>
</p>

<%= link_to 'Editar', edit_program_path(@program) %> |
<%= link_to 'Atras', programs_path %>